exult/exult

drag.cc
Trying putting an open container to itself resulted in different indications depending on the hackmover being on or off, this fixed now to a form consistent with the original game.
=> red X when putting container to itself

mapedit/shapeedit.cc
Per GTK API documentation:
Removed calls to g_free on uncopied iters
changed g_free to gtk_tree_iter_free for copied iters
=> Fixed bug caused by calling g_free on GtkTreeIter

txtscroll.cc
=> Fixed OOB memory access in TextScroller used in the credits.

audio/Audio.h, audio/Midi.h, gamemgr/modmgr.h, gumps/Actor_gump.h, gumps/AudioOptions_gump.h, gumps/Book_gump.h, gumps/CombatStats_gump.h, gumps/Face_stats.h, gumps/File_gump.h, gumps/Gamemenu_gump.h, gumps/GameplayOptions_gump.h, gumps/Gump.h, gumps/Gump_button.h, gumps/Gump_widget.h, gumps/InputOptions_gump.h, gumps/ItemMenu_gump.h, gumps/MiscOptions_gump.h, gumps/Modal_gump.h, gumps/Newfile_gump.h, gumps/Notebook_gump.h, gumps/Paperdoll_gump.h, gumps/Scroll_gump.h, gumps/Sign_gump.h, gumps/Slider_gump.h, gumps/Stats_gump.h, gumps/Text_gump.h, gumps/VideoOptions_gump.h, gumps/Yesno_gump.h, headers/exceptions.h, usecode/ucmachine.h
Solution per analogiam to boost::noncopyable, see http://bajamircea.github.io/coding/cpp/2017/02/22/noncopyable-adl.html
=> Use derivation instead of macro to prevent copying

effects.cc, effects.h
I thought it might be reasonable to simplify the code by using STL instead of hand-made linked lists.
On top of that, I have added some RAII - hopefully - and simplified the code even more.
Special_effects to go, they are a logical next step, but I prefer to keep those PRs separate for clarity (and I'm certain there's at least one more place in the code with hand-made lists).
If you prefer it organized in any other way - I'm open for suggestions.
As for the code itself - lambda capture is a matter of taste, I decided to do it by value as raw pointers are dealt here with.
What I also do necessarily like about readability is the `remove`/`remove_if` member call on list, and I was a bit tempted to change that to standard erase/remove idiom (as done e.g. with `vector`)...
=> Store Text_effect in std::list

tools/wuc.cc
The 1.6 release fails to complie on Xcode 12.1 because of "byte" conflicting with "std::byte".  I noticed that this was already
renamed "byteval" in the master branch (part of the larger set of changes in d7998ecace00daa0469494377f916db386396406). I thought it would be useful to backport this to the v1.6.x branch as well.
I don't know anything about exult's release cycle or if there is going to be any more releases from 1.6.x but I am just trying to get the Homebrew formula for exult building again.
=> [1.6.x branch] Fix compile for wuc.cc on Xcode12

mapedit/studio.cc
mapedit/studio.cc
function add_to_tree, convert fname argument of U7exists to lowercase
Fixes issue #65
=> ExultStudio fix file duplicates on case sensitive file systems

mapedit/exult_studio.glade, mapedit/shapeedit.cc, mapedit/shapegroup.cc, mapedit/shapegroup.h
mapedit/shapedit.cc + exult_studio.glade
Negative Warmth values : unsigned int -> int, lower bound of adjustment
Frame usecode : Fix wrong column to retrieve function name
mapedit/shapegroup.cc+h + exult_studio.glade
Add two builtin groups for Frame usecode and Light
Fixes issue #73
=> ExultStudio : Fixes in Shape Groups and in Shape Editor

configure.ac, tools/Makefile.am
configure.ac
Replace the pkg-config requirement of GDK by GDK-PIXBUF
tools/Makefile.am
Replace the CFLAGS/LIBS variables from pkg-config GDK by GDK-PIXBUF
=> Gdk-pixbuf is an independent package from Gdk

tools/gnome_shp_thumbnailer.cc
tools/gnome_shp_thumbnailer.cc
Use the same pragma gcc diagnostic ignored as mapedit/studio.cc
=> Silence g++ and clang++ over gnome_shp_thumbnailer.cc

shapes/u7drag.cc
shapes/u7drag.cc
Shapes have different names and name lengths : do no use static,
Drop Targets in Linux receive the URL minus the file:// prefix,
Recognition test handled in reverse False vs True.
=> Fix Drop Target file name recognition

mapedit/locator.cc
Studio : Locator window, use Drag mode to move the reference location of the Avatar :
The reference location jumps at start of the Drag if the cursor was not exactly centered on the reference location.
Reason : the Delta ( drag_relx & drag_rely ) is applied with the wrong sign, it is added, should be subtracted.
mapedit/locator.cc
Subtract drag_relx/y to mx/y instead of adding them.
=> ExultStudio : Fix initial jump of reference point in Locator used in Drag

docs/Makefile.am
To align to Win32 and macOS/iOS :
install Readme.html ( Exult ), faq.html ( FAQ ), exult_studio.html( ExultStudio ) and dependent images
into /usr/share/doc/exult and /usr/share/doc/exult/images on Linux.
=> Install three Documentation HTML and dependent images in Linux

audio/midi_drivers/FMOplMidiDriver.cpp, audio/midi_drivers/FMOplMidiDriver.h, audio/midi_drivers/FluidSynthMidiDriver.cpp, audio/midi_drivers/FluidSynthMidiDriver.h
Some changes in MIDI for Exult :
- Put a cosmetic change in FMOpl MIDI to silence a compiler warning,
- Get the synth.default-soundfont in FluidSynth to supply a default SoundFont when fluidsynth_soundfont is missing in exult.cfg.
- Remove the explicit FluidSynth SoundFont unload that cause warnings.
=> FluidSynth MIDI : Use default SoundFont when no fluidsynth_soundfont

Makefile.am, audio/Makefile.am, conf/Makefile.am, content/Makefile.am, content/bg/Makefile.am, content/bgkeyring/Makefile.am, content/islefaq/Makefile.am, content/si/Makefile.am, content/sifixes/Makefile.am, data/Makefile.am, docs/Makefile.am, files/Makefile.am, mapedit/Makefile.am, shapes/Makefile.am, tools/Makefile.am, usecode/Makefile.am, usecode/compiler/Makefile.am, usecode/ucxt/Docs/Makefile.am, usecode/ucxt/data/Makefile.am
Revalidate `make dist` on Autotools builds [ Linux and MacOSX ]  
```
Makefile.am
Respect (AM_)LIBTOOLFLAGS in CXXLINK
Makefile.am and all nested Makefile.am
Update the source file lists
Separate the original data files from the built data files
and make the built datafiles "nodist_'
```
=> Update all Makefile.am - Autotools driven Build for Linux and MacOSX

mapedit/shapedraw.cc
The Rotate frame button in the Container Editor and the Object Editor does not work : the shape becomes black instead of rotated.
The `Shape_draw::draw_shape_centered` method ignores the two editors convention of ORing the frame number with 32 to ask for a rotated frame. It leaves the shape black as its frame number exceeds the frame count of the shape.
Ensure that frame numbers in the range 32 .. 32 + frame count - 1 are accepted too.
=> Studio : Fix Rotate button in Container and Object Editors

effects.cc, effects.h
Technically a method can `delete this` but should return immediately afterwards. This is kind of a workaround for address sanitizer being picky about that, but in fact it also makes a clear indication in the code that the object acquires its own handle. 
Branch name stems from Cloud_effects that would trigger the problem with asan ;)
=> Make address sanitizer happy about Special_effects being removed

mapedit/contedit.cc, mapedit/eggedit.cc, mapedit/exult_studio.glade, mapedit/npcedit.cc, mapedit/objedit.cc, mapedit/shapedraw.cc, mapedit/shapedraw.h, mapedit/shapeedit.cc, mapedit/studio.cc, mapedit/studio.h
Contrarily to the discussion in issue #71, the code compiles and runs on Linux and on Windows, I figured out what the Drag and Drop WIN32 problem was and fixed it.
By the way, this highlighted that I should have had more compilation failures. Indeed, the three stand alone shape displays of the Shape Editor [ Gump, Body and Explosion ] claim to be Drop targets ( enable_drop ) but do not use the WIN32 path.
=> Studio : Provide and use a new C++ class "ShapeSingle" for single Shape display

npcnear.h, tqueue.cc, tqueue.h
Some code clean-up, mostly moving from bare loops to STL algos/ranged for loops.
I actually wanted to use upper bound in `activate0`, too, but it seems objects are deletign themselves sometimes, which ends in double-free again, so I gave it up, temporarily at least.
@marzojr two questions related to tqueue:
1. What will you say about using a different data structure? As it's supposed to be sorted, multimap with time being the key seems more viable than list. I was also thinking about priority queue, but it does not allow random access.
2. What do you think about including Boost? Some classes like Tqeue could greatly benefit from it, e.g. thanks to its filter_iterator (which currently Tqeue_iteratator replaces). License-wise that should not be a problem, technically not a big issue either, …
=> Simplify tqueue

exult.cc, mapedit/chunklst.cc, mapedit/chunklst.h, mapedit/combo.cc, mapedit/combo.h, mapedit/contedit.cc, mapedit/eggedit.cc, mapedit/npcedit.cc, mapedit/npclst.cc, mapedit/npclst.h, mapedit/objedit.cc, mapedit/shapedraw.cc, mapedit/shapelst.cc, mapedit/shapelst.h, mapedit/studio.cc, mapedit/studio.h, shapes/u7drag.h, windrag.cc, windrag.h
This is a proposal for a rework of the Drag and Drop code in Exult and Studio under Windows, as discussed in Issue #71.
In Windows, when the Drag and Drop from Studio to Exult was created, SDL for Exult and GTK+ for Studio only supported receiving WM_DROPFILES messages, and GTK+ supported sending/receiving Drag and Drop messages but only from/to the windows of the current GTK+ application. In other words, there were no way to post a Drag and Drop message from Studio to Exult.
Under Windows, Exult _and_ Studio have their own specialized Drag and Drop code paths to overcome this lack of a working Drag and Drop protocol. This code is in `windrag.h` and `windrag.cc`. Whereas Exult displays a single window acting as an entire Drag and Drop receiver, Studio has many windows and many Drag and …
=> Prototype : Studio in WIN32 : Use GTK+ 3 OLE2 provided Drag and Drop instead of Windrag

files/Flex.h
Here is a fix for savegame corruption when not using zip compression.
The size of "filename" field in the flex file should be 13 bytes, but currently Exult only writes 12 bytes.
=> Fix savegame corruption when save_compression == 0

shapes/data_utils.h
For lost changes in Shape Editor :
On a Shape object without Frame Names, create Frame Names with the Shape Editor, Add, OK, the Frame Names are lost on the Shape Editor exit.
On a Shape object created by a patch, with Frame Names, or on a Shape Object given Frame Names by a patch, alter the Frame Names with the Shape Editor, Add, OK, the Shape loses all its Frame Names at Shape Editor exit.
Same with Frame Flags, Frame HPs, Frame Usecode, Object Paperdoll, Brightness and Warmth.
Reason : the clean_vector function called by all clean_invalid_.. functions has its removal test wrong.
Should fix Issue #121 
Sincerely
Dragon-Baroque
=> Studio clean_vector

mapedit/combo.cc, mapedit/contedit.cc, mapedit/objedit.cc, mapedit/shapegroup.cc, mapedit/shapelst.cc, mapedit/studio.cc, shapes/shapevga.cc, shapes/shapevga.h
Proposal to solve issue #122.
At the end of `Shapes_vga_file::read_info`, scan the Shapes that are monsters and which hold the obsolete monster flags can_teleport, can_summon, can_be_invisible.
Set these flags into shape_info.txt Actor info - seen in the Studio Shape Editor as NPC Flags, and 
Remove these flags from Monster info in monster.dat.
For each such Shape, produce under Exult or under Exult Studio on cerr/stderr a message like 
`Shape 1298 is a monster that can teleport, teleport flag moved from Monster info ( monster.dat ) to Actor info ( shape_info.txt ) as NPC flags.`
Real example taken from Glimmerscape Mod from SourceForge. Shape 1298 is the Wisp.
Missing : set modified flag which would cause a warning at Studio exit from a needed Save. At this point, Save All rewrites …
=> Transfer obsolete monster flags from monster.dat to shape_info.txt

gumps/Face_stats.cc, gumps/GameplayOptions_gump.cc
Added vertical status bars so it can be used when on a widescreen monitor(or windowed) to make use of the empty space on the left and right of the game window if using original game area.
Decided to put them in two groups of 4 as to not need to squish them all on one side which could be done without overlap but looks awful.
Typical use case(how it looks @ 1920x1080 or 2560x1440(16:9))
New Option in Gameplay
Will center potraits up to double potrait width...
When you have really large black bars...
Two more to show nothing is broken...
=> Add vertical status bars

content/bg/Makefile.mingw, content/bgkeyring/Makefile.am, content/bgkeyring/Makefile.mingw, content/islefaq/Makefile.mingw, content/makefile_builder.sh, content/si/Makefile.mingw, content/sifixes/Makefile.am, content/sifixes/Makefile.mingw
The various Makefile.mingw to install the game mods ( si, sifixes, gb, bgkeyring ) all use 
`mkdir forgeofvirtue/mods` or `mkdir silverseed/mods`.
Replace those by `mkdir -p ...` to ensure that one may install all mods.
1. Actually changed only into `makefile_builder.sh`,
2. Then regenerated all Makefile.sh and Makefile.mingw using `LC_ALL=C ./makefile_builder.sh`.
Even with LC_ALL=C, the produced Makefiles change the place of `Laurianna.shp` and `Laurianna_Paperdoll.shp`.
Sorry about that.
On the other hand it looks like `map_en.shp` was missing fron `sifixes`.
I don't know whether that is serious.
=> Install script changes for game mods

autogen.sh
The existing `autogen.sh` assumes it is being run from the source directory.  This causes problems if the build is being managed by a tool which is running from another directory.  This patch modifies the script to change to the source directory before rerunning autotools.
=> Fix out-of-tree autogen

Makefile.am, acinclude.m4, sdl_main.cc
On Android, SDL replaces the `main()` symbol with `SDL_main()`, which results in a link error if we try to link an executable.  This is actually a more generic concept in SDL that is turned on by default in android builds.  This patch adds support for detecting when a platform enables `SDL_main()` and adds a wrapper with a real `main()` to call it when building an executable.
=> Detect SDL with SDL_main

configure.ac, mapedit/u7shp.cc
Commit 1 of 1
configure.ac
Handle Gimp Ver.Rel.Mod where Rel >= 10
mapedit/u7shp.cc
Move gimp.h and gimpui.h under the warning deactivate frame
Add 2 new warning deactivates
Do no enable the GTK .. Deprecated checks
=> Fix Gimp Plugin compilation on Linux

Makefile.am, configure.ac, macosx/macosx.am
The existing build structure always tries to build exult as an executable.  This ends up causing link errors when building for android.  This patch introduces a configure option to build the entire exult codebase into a library instead of an executable.  This will enable android builds to opt out of the executable while still building the library which the app will load at runtime.  This configure option is disabled by default, so builds on other platforms will still generate a monolithic executable like they always have.
=> Add option to build Exult as a library

usecode/compiler/uclex.ll, usecode/compiler/ucparse.yy
usecode/compiler/uclex.ll + ucparse.yy
CLang does not support -Wredundant-tags
=> Fix CLang warnings in Usecode Compiler

.github/workflows/ci-linux.yml, configure.ac
./configure.ac
Complete the handling of option --with-cxx
Handle the OVERRIDE_CXX environment variable
Disable the GIMP plugin build if pkg-config is not installed
Remove a few spurious spaces and tabs
List a larger set of option settings, including the compiler
For the replacement commit : remove the display of ( nonexistent ) `enable_macosx_studio_support`
=> Support C++ compiler override in configure.ac

exult.cc
If Exult tries to start in windowed mode, the scaling doesn't work right and screen touches don't align with the game cursor.  Force the game to always be in fullscreen for Android.
=> Fullscreen only on Android

gamemgr/modmgr.cc
Existing code assumes paths returned by `U7ListFiles()` will have the same form as the path passed in, but in some cases, if a relative path is passed in, the paths it returns will be resolved to absolute pathnames.  This modifies modmgr code to extract the mod name by working backward from the end of the string rather than the current offset scheme.
=> Fix mod name extraction from path

imagewin/imagewin.cc
This probably doesn't matter for standalone executables that fully terminate the process when the game exits, but on Android, the game is loaded as a shared library and it is not reliably unloaded when the game exits.  In cases where the library is kept in memory, a subsequent attempt to start the game will find the previous run's `SDL_Window` still allocated, and if we don't clean it up here, the subsequent attempt to call `SDL_CreateWindow()` will crash.
=> Fix crash when restarting game on Android

.gitignore
The Android app will end up organizing java souces in a directory structure that includes a folder named 'exult'.  The current .gitignore causes any folder named 'exult' to be ignored.  This patch changes to only ignoring files/folders named 'exult' at the top level to avoid interfering with android sources.
=> Only match top-level exult in .gitignore

android/Makefile.am, configure.ac
This downloads the SDL source tree and links the java sources into the staged Android app build tree.  This downloaded source tree will also be used in later patches for the NDK build of libsdl.
=> Add SDL Android App Java sources

android/Makefile.am, android/app/src/main/cpp/dependencies/sdl/0001-temporarily-disable-hidapi.patch
The android app is having trouble loading hidapi.  Need to circle back and figure out how to load it correctly, but temporarily removing the dependency on it for now.
=> Temporaily disable dependency on hidapi

android/app/src/main/cpp/CMakeLists.txt, android/app/src/main/cpp/dependencies/CMakeLists.txt, android/app/src/main/cpp/dependencies/build_dependency.cmake, android/app/src/main/cpp/dependencies/ogg/CMakeLists.txt, android/app/src/main/cpp/dependencies/ogg/CMakeLists.txt.in
First patch adds the dependency framework, and the second adds the Ogg dependency to show how the framework is used:
- Add cmake scripts to support pulling in and building NDK-level dependency libraries for Exult.
- Download and build the Ogg library with the NDK toolchain.
Other dependencies to follow after these are merged.
=> Add dependencies framework and Ogg dependency

audio/AudioMixer.cc
The existing 20Hz buffering for ogg/vorbis playback isn't sufficient on android.  It results in stuttering when using digital music on both an emulated android device on a laptop and on two native android devices.  Increasing to 5Hz buffering.
Note: This value was chosen based on empirical testing on a Kindle Fire tablet.  6Hz and above resulted in stuttering with digital music enabled.
=> Fix ogg/vorbis stuttering on Android

android/Makefile.am
`android/Makefile.am` was using a couple of GNU Make extensions which were triggering warnings from automake.  One was related to using `%` pattern rules, which can be mitigated by changing to [static pattern rules](https://www.gnu.org/software/make/manual/html_node/Static-Usage.html).  The other was related to using `$(dir $@)` to get the directory path of a build target, which can be changed to the [automatic variable](https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html) `$(@D)` which does not generate automake warnings.
=> Clean up automake warnings in android/Makefile.am

android/lib/include/TouchUI_Android.h, android/lib/src/TouchUI_Android.cc
The current code for the Android dpad creates a virtual joystick with `SDL_JoystickAttachVirtual()` and then opens it with `SDL_GameControllerOpen()` for all subsequent interaction.  In practice, it only gets used as a joystick and does not have a hat or buttons, so it is more efficient to open it with `SDL_JoystickOpen()`.  In addition, [this commit](https://github.com/libsdl-org/SDL/commit/1a17ab30e17f22c390caa1403f32dfac03532dff#diff-da9344d94c66b8c702a45e7649f412039f08bba83bd82de33f5c80ea9c8c39d5R488-R491) introduces code that causes `SDL_GameControllerOpen()` to fail for virtual joysticks, but `SDL_JoystickOpen()` continues to work fine.  SDL will have a fix for [this issue](https://github.com/libsdl-org/SDL/issues/5662) in v2.0.24, but in the mean time, `SDL_JoystickOpen()` is the …
=> Use SDL_Joystick API for Android virtual dpad

imagewin/imagewin.h
There was no documentation for the `VideoModeOK()` method, and some of the calling code appears to be using it incorrectly.  This patch simply adds some documentation for the return value of the function.
=> Document VideoModeOK() return value

imagewin/imagewin.cc
This message was already ifdeffed out for iOS; also disable it for Android.
=> Clean up unnecessary log message about windowed surfaces

android/app/src/main/cpp/exult_android_main.cc
Simply returning from the NDK entrypoint function does not clean up global resources since the process has not terminated, which can cause problems with Exult as it assumes the entire engine terminates upon return from `main()`.  Calling `exit()` ensures full cleanup so that the Android version behaves more like a standard process exiting.  The need for this surfaced when debugging problems with enabling scalers on Android.  They work the first time the app launches, but fail on subsequent runs.  With this patch applied, scalers work consistently on every run.  This patch is a workaround which is technically masking real bugs with proper resource cleanup in the code, but as the entire Exult codebase is written to assume complete cleanup upon return from main, there may be many small …
=> Use exit() to terminate NDK code

imagewin/imagewin.cc, imagewin/imagewin.h
These patches clean up inconsistencies in `Image_window::VideoModeOK` and clean up some unused fields in `Image_window::Resolution`.  It looks like there is probably more cleanup and simplification possible in `Image_window`, but it would be more intrusive and risk regressions, so holding off on that for now.
These resolve https://github.com/exult/exult/issues/220
=> Clean up some inconsistencies and unneeded code in Image_window

configure.ac
configure.ac
After Pkg-Config detection, fail if not found
Remove tests over Pkg-Config existence, keep then branch, remove else branch
Comment out SYSLIBS set to X11 when building with Exult Studio support
=> Mandatory Pkg-Config in Linux and MacOS builds for Exult 1.9+

audio/midi_drivers/timidity/timidity.cpp, audio/midi_drivers/timidity/timidity.h, gumps/Gamemenu_gump.cc, shapeid.cc
First commit is for two leftovers of the exult_silent_clang_sdl Pull Request :
- Wrong setting of a closing pragma,
- Some unneeded cast.
Second commit fixes Timidity under Linux
- Wrong Linux detection caused wrong Endianness
- The `timidity.cfg` was not found at its expected location `share/exult`,
- The `timidity.cfg` was not properly parsed when it contained part line comments.
=> Exult silent clang sdl fix

conf/XMLEntity.cc
From issue #238, Exult XML Config part :
- Store XML terminals on one line: `<alsa_port>65:0</alsa_port>`
- Indent nesting by two spaces instead of one
=> Pretty print exult.cfg XML

audio/midi_drivers/ALSAMidiDriver.cpp, audio/midi_drivers/ALSAMidiDriver.h
From issue #238, Hardware MIDI Synth support in Linux part :
Instead of _failing_ on default ALSA MIDI port `65:0` and _reverting_ to `FMOpl`,
_list_ the available MIDI devices, then _choose_ one, preferably hardware.
=> Exult on Linux : Support Hardware MIDI synths

mapedit/exult_studio.glade
To fix issue #249, alter `mapedit/exult_studio.glade`, GtkScrolledWindow `scrolledwindow2` :
Replace `hscrollbar-policy` `never` ( switches to default `automatic` ) by `min-content-height` `360` ( to ensure a reasonably sized Tree View, such that the `Forge of Virtue` file list fits)
=> Exult Studio : Make File List left panel vertically scrollable

mapedit/chunklst.cc, mapedit/combo.cc, mapedit/gtk_redefines.h, mapedit/npclst.cc, mapedit/objbrowse.cc, mapedit/objbrowse.h, mapedit/shapelst.cc
To complete issue #249 :  
- Declare a ( static ) Scroll Event Handler in `mapedit/chunklst.h + combo.h + npclst.h + shapelst.h`
- Create and Bind a Scroll Event Handler in the browser constructor in ` mapedit/chunklst.cc + combo.cc + npclst.cc + shapelst.cc`
- Implement the Scroll Event handler in ` mapedit/chunklst.cc + combo.cc + npclst.cc + shapelst.cc` emulating the GTK effect of a mouse wheel event _on the vertical scroller_ :
1. Mouse wheel Scroll Events _on non macOS_ are in click units, then send a Scroller move of
`numberOfClicks * ( browserHeight ** 2/3 )`,
3. Mouse wheel Scroll Events _on macOS_ are in pixel units, then send a Scroller move of `numberOfPixels`.
=> Support mouse wheel vertical scrolling in shape browsers

mapedit/exult_studio.glade
From issue #249 reopen :
Ensure that the FileList treeview has its larger width - set by the Groups page - at start, by making the Groups page active by default.
=> Ensure that Studio's FileList window has its full width at start

gumps/VideoOptions_gump.cc, mapedit/chunklst.cc, mapedit/chunklst.h, mapedit/combo.cc, mapedit/combo.h, mapedit/exult_studio.glade, mapedit/npclst.cc, mapedit/objbrowse.cc, mapedit/shapedraw.cc, mapedit/shapedraw.h, mapedit/shapelst.cc, mapedit/studio.cc, mapedit/studio.h
gumps/VideoOptions_gump.cc
Add resolutions up to 1600
Pair all resolutions in 16:10 ( original 320x200 ) and 4:3
mapedit/exult_studio.glade
Name the GtkBox widget in the Menubar to add the Zoom widgets
mapedit/studio.cc + h
Parse and store the command line Zoom options
Build and handle the Menubar Zoom widgets
Handle keyboard + and - including Keypad to change the Zoom scale
mapedit/objbrowse.cc, chunklst.cc, combo.cc, npclst.cc, shapelst.cc
[ Debug ] Display event messages for the Scrollers, the Wheels
mapedit/chunklst.cc + h, combo.cc + h
Move the Scrollers setup when Zooming change into a new setup_info
Switch the Scrollers to smoother - part row - than full row
mapedit/shapedraw.cc + h
Implement Zooming in Shape_draw::show, ExultStudio::shape_image
Rework Shape_single …
=> Zoom Shapes in Studio for HiDPI screens

mapedit/chunklst.cc, mapedit/combo.cc
Commit 1 of 1:
mapedit/chunklst.cc + combo.cc
Adjust the scroller value at zoom change to remain in place
Follow up of PR #281 : Try to remain in place in the Combo browser and in the Chunk browser when changing the Zooming scale.
=> Studio Shape Zooming : Follow vertical scroller value changing scale

gamerend.cc, mapedit/chunklst.cc, mapedit/shapedraw.cc, objs/chunkter.cc, objs/chunkter.h
Various fixes in Exult and Studio around the Chunks Browser and the Map Editor:
- Studio : In large Zooming, the single Shape displays ( like the main Shape in the Shape Editor ) could be barred by a white line.
The fix is a reset of the Cairo clip in `Shape_draw::draw_shape_centered` in `mapedit/shapedraw.cc` when enlarging the GtkDrawingArea.
- Studio : The Chunks Browser displays damaged chunks when those contain a mix of `non RLE` flats and `RLE` flats.
The fix is a two passes display in `Chunk_chooser::render_chunk` in `mapedit/chunklst.cc` :  `non RLE` shapes, followed by `RLE` shapes like in `Game_render::paint_map` in `gamerend.cc`, and a neutering of the invalid default origin `-1, -1` of `non RLE` shapes.
- Exult : The main map painter has a wrong sign pixel shift in the second …
=> Fixes in Chunks and Map Editor

mapedit/chunklst.cc, mapedit/combo.cc, mapedit/npclst.cc, mapedit/shapelst.cc
This Pull Request, to complete the Issue #278, contains
- Two cosmetic fixes into `combo.cc`,
- A check to prevent an horizontal scroller bar to overflow on the right when the Zoom decreases,
- A better tracking of the _current_ Shape, that is, either the selected Shape, or the leftmost topmost visible Shape, to ensure that it remains visible while the Zoom changes, the Shape browser, the Npc browser, the Combo browser, the Chunk browser.
=> Follow current shape or selected shape while changing zoom

gamemap.cc, gamerend.cc
Fixes Issue #283 :
Discrepancy in the chunk cache between its build in `Game_map::read_map_data` and its use in `Game_render::paint_map` when the Edit Terrain mode is enabled.
The Smooth Scrolling mode in commit 237dc6881 requires one more chunk at the right and at the bottom in `Game_render::paint_map` but the chunk cache in `Game_map::read_map_data` was not altered.
This PR increases the chunk limits when building the chunk cache.
=> Fix enabling Edit Terrain after Locating a chunk near a superchunk boundary

cheat_screen.cc
When expecting a Name, a Decimal number or an Hexadecimal number, the Cheat menu crashes when the user holds a control key ( Shift, Control, ... ) for some time.
Then SDL sends a key event, whose SDL_Keysym is outside the range 0..255 and then `std::isdigit`, `std::isxdigit`, `std::isalnum` index a `ctype` array outside its bounds.
Ensure that the SDL_Keysym is in the range 0..255 or return false to the check.
=> Fix crash in Cheat menu when holding Shift for some time

gamemgr/modmgr.cc, gamemgr/modmgr.h, mapedit/exult_studio.glade, mapedit/shapelst.cc, mapedit/studio.cc
gamemgr/modmgr.h + cc, mapedit/studio.cc
Set default codepage to ASCII : 7 bits with reuse
mapedit/exult_studio.glade, mapedit/studio.cc
Add codepages ASCII 7 bits and CP-850 into Game Information -> Character Set combo box
mapedit/shapelst.cc
Add missing conversions to UTF8 in update_statusbar
mapedit/studio.cc
Display half size encoding table when using ASCII 7 bits
Display byte 08, produces binary 08 unless reused by ASCII
Conversion from ASCII to UTF8 : front the conversion by a move of diacritics to PC437 location
Conversion from UTF8 to ASCII : back  the conversion by a move of diacritics to control bytes
This is a proposal related to the issue #334.
=> Support Ultima VII German / French 7 bit ASCII codepage with reuse of control bytes for diacritics

.github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, Makefile.mingw, configure.ac, mapedit/Makefile.am, mapedit/exult_studio.glade, mapedit/npcedit.cc, mapedit/shapeedit.cc, mapedit/shapefile.cc, mapedit/shapelst.cc, mapedit/studio.cc, mapedit/studio.h
Commit 1 of 1
.github/workflows/ci-linux.yml + ci-macos/yml + ci-windows.yml
Add the ICU to the required components
Makefile.mingw + configure.ac + mapedit/Makefile.am
Add the ICU CFLAGS and LIBS to the build of Studio
mapedit/exult_studio.glade
Fix two windows that closed badly whex clicked on the cross
Remove the not supported ISO-8859-16
mapedit/npcedit.cc + shapeedit.cc + shapefile.cc + shapelst.cc
Use the explicit conversion function, avoid string replicas
mapedit/studio.h
Replace the scaffolding classes utf8Str and codepageStr
by explicit conversion functions
mapedit/studio.cc [ the only source with ICU includes ]
Implement the conversion functions, no longer any retry
Use std::string as result
=> Exult Studio uses the ICU to convert strings from and to UTF-8

actorio.cc, mapedit/objedit.cc
Commit 1 of 1:
actorio.cc
Remove a NPC name check for codebytes between 20 and 7f :
Original German / French Ultima VII diacritics are in 01 .. 1f
ISO-8859 / CP1252 etc diacritics are in 80 .. ff
mapedit/objedit.cc
Add a missing conversion Codepage to UTF8 to display the name
=> Fix Studio and Exult handling of Objects and NPC names with diacritics

files/utils.cc
Save configuration file and savehome_dir to ~/config/settings/exult 
Use data from ~/config/non-packaged/data/exult (system data folder is read-only so users can't install their game data there)
=> Add support for Haiku's layout

shapes/u7drag.cc
This fixes issue #390 
=> BackPorted from exult-sdl3 branch
shapes/u7drag.cc
Shape, Chunk, Npc, Combo : Remove trailing zero from encoded size
=> Remove trailing zero from Drag and Drop file name

mapedit/studio.cc
1. Studio sets `<DATA>` two times, the first one is correct with `setup_data_dir`, the second one overrides it improperly with the default or config path. Remove that second setting.
2. Obtain the current `<DATA>` to find `exult_studio.glade`.
Discussion in issue #408
=> Fix <DATA> spurious override in Studio, find properly exult_studio.glade

.github/workflows/ci-macos.yml, configure.ac
Set `enable_mt32emu` to yes in `configure.ac`
Add `brew install mt32emu` in `.github/workflows/ci-macos.yml`.
Cannot do the same for Linux as MT32Emu is not packaged in Ubuntu 22.04.
=> Build MT32Emu MIDI support by default

version.cc
(under FreeBSD)
`exult --version` compiled with Clang:
`Compiler: GCC FreeBSD Clang 14.0.5`
fixed:
`Compiler: FreeBSD Clang 14.0.5`
`exult --version` compiled with GCC:
`Compiler: GCC 11.3.0`
I've searched code but I didn't found why is FreeBSD showing up in compiler version section.
=> Fix Clang compiler name

Makefile.mingw, actors.cc, configure.ac, objs/objs.cc, schedule.cc, usecode/ucscriptop.h
@marzojr, will you accept the following PR :
I tried to compile ( GCC and CLang ) with C++ 20, and I got two new warnings :
1- `arithmetic between different enumeration types ‘Ucscript::Ucscript_ops’ and ‘Actor::Frames’ is deprecated [-Wdeprecated-enum-enum-conversion]` over `actors.cc` and `schedule.cc` about `(Ucscript::npc_frame + Actor::kneel_frame)` and similar.
2- only in GCC :
```
In function 'void Write1(uint8*&, uint8)',
inlined from 'void Write2(Dest&, uint16) [with Dest = unsigned char*]' at ../files/utils.h:309:8,
inlined from 'static std::unique_ptr<unsigned char []> Shape_frame::encode_rle(unsigned char*, int, int, int, int, int&)' at vgafile.cc:313:8:
../files/utils.h:296:16: warning: null pointer dereference [-Wnull-dereference]
296 |         *out++ = val;
| …
```
=> Silence C++ 20 warning

mapedit/bargeedit.cc, mapedit/chunklst.cc, mapedit/combo.cc, mapedit/compile.cc, mapedit/contedit.cc, mapedit/eggedit.cc, mapedit/execbox.cc, mapedit/exult_studio.glade, mapedit/locator.cc, mapedit/maps.cc, mapedit/npcedit.cc, mapedit/npclst.cc, mapedit/objbrowse.cc, mapedit/objedit.cc, mapedit/paledit.cc, mapedit/shapedraw.cc, mapedit/shapeedit.cc, mapedit/shapegroup.cc, mapedit/shapelst.cc, mapedit/studio.cc, mapedit/studio.h, mapedit/u7shp.cc, mapedit/ucbrowse.cc
In Studio : 
- Replace GTK `TRUE` and `FALSE` by C++ `true` and `false` ( are identical ), overall in Studio
- Replace `gtk_widget_show` and `gtk_widget_hide` by `gtk_widget_set_visible`, overall in Studio, obsolescent in GTK+ 3, removed from GTK 4,
- Provide an `exult_widget_hide` in `studio.cc` for use in `exult_studio.glade` which cannot use `gtk_widget_set_visible` because of its boolean parameter,
- Add `DISABLE_DEPRECATION_WARNINGS` into the common `studio.h` and into the independent `u7shp.c` from non strict GTK.
=> Replace GTK TRUE+FALSE by C++ true+false, widget show+hide by set visible

.github/workflows/ci-android.yml, .github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml, .github/workflows/codeql.yml, .github/workflows/coverity-scan.yml, .github/workflows/snapshots-android.yml, .travis.yml, .travis/script.sh, INSTALL, README.MacOSX, android/README.md, android/app/src/main/cpp/dependencies/exult/CMakeLists.txt.in, exult.spec.in
`autoreconf -f` overwrites `./INSTALL` with its version stored in `/usr/share/automake-1.16/INSTALL`.
- Replace all occurences of `autoreconf -f -v -i` by `autoreconf -v -i`
- Bring into `INSTALL` two lines out of the `automake 1.16` version of `INSTALL`
=> Do not autoreconf -f for it overwrites ./INSTALL

configure.ac
Normalize all POSIX platforms using GCC or CLang to use `-pthread`,
Comment a bit the support state of the various platforms.
Proposition to #436.
=> Rework configure.ac for PThread, comment OS choices

.github/workflows/ci-freebsd.yml, Makefile.am, audio/OggAudioSample.h, audio/midi_drivers/ALSAMidiDriver.h, configure.ac, mapedit/Makefile.am, tools/Makefile.am
To finish the port to FreeBSD and remove the spurious clauses for `/usr/local/include` and `/usr/local/lib` :
- in `configure.ac`
- Remove `/usr/local/include`
- Replace `AC_CHECK_HEADERS` by `PKG_CHECK_MODULES` to locate the libpng
- Enforce the dependencies of libpng : Studio and Gnome Thumbnailer
- in `audio/OggAudioSample.h`
- Silence warnings of `vorbisfile.h` when out of `/usr/include`
- in `audio/midi_drivers/ALSAMidiDriver.h`
- Silence warnings of `alsa/pcm.h` when out of `/usr/include`
- in `Makefile.am` + `mapedit/Makefile.am` + `tools/Makefile.am`
- Add `$(PNG_CFLAGS)` to the include list
- Replace explicit `-lz` and `-lpng` by `$(ZLIB_LIBS)` and `$(PNG_LIBS)`
- in `.github/workflows/ci-freebsd.yml`
- Remove the `/usr/local/include` and `/usr/local/lib`
=> Cleanup Exult build on FreeBSD, remove /usr/local explicit references

.github/workflows/ci-freebsd.yml, audio/OggAudioSample.h, configure.ac, exult.cc, imagewin/Makefile.am, shapes/Makefile.am
Some more fixes
- `.github/workflows/ci-freebsd.yml` : Align `./configure` with the other `./configure` in the workflows that use it,
- `audio/OggAudioSample.h` : Silence `vorbisfile.h` with GCC when Vorbis is not in `/usr/include`
- `exult.cc` : Silence `SDL_syswm.h` when SDL is not in `/usr/include`
- `imagewin/Makefile.am` + `shapes/Makefile.am` : Missing `$(PNG_CFLAGS)` when libPNG is not in `/usr/include`
- `configure.ac` : Remove `/usr/X11R6/include` from NetBSD build, NetBSD is at `X11R7` anyway.
=> Cleanup for libpng and silence some warnings in NetBSD

server/objserial.cc, server/objserial.h
To fix issue  #458 :  
-  `server/objserial.cc` : Replace the `size_t` string length by an `uint32_t` in `Serial_in + out::operator<<(string)`.
No longer any need to alter the Keyring `combo.flx`.
=> Client - Server protocol : limit strings to 4G

audio/midi_drivers/ALSAMidiDriver.cpp, shapes/vgafile.cc
Switching from GCC 13 to GCC 14, Exult fails to compile with undefined `std::copy_n` which has been moved off to `algorithm`.
- Add `#include <algorithm>` to `audio/midi_drivers/ALSAMidiDriver.cpp` and `shapes/vgafile.cc`
=> Fix missing std::copy_n with GCC 14

npcnear.cc, npcnear.h, npctime.cc, schedule.cc
- Don't make bed when being awaken from sleep
- This involves:
1. Making sleep timer not clear sleep flag: Gorlab Swamp usecode checks for it to determine who is awake.
2. Fixing Npc_proximity_handler::handle_event that prevents wake-up with sleep flag set due to change above.
3. Disable party members from being woken from sleep schedule by Avatar.
4. Make awake checks depend on frame-rate and slightly tweaking the probabilities to account for the above.
Fixes #297
=> Fix Gorlab Swamp

content/sifixes/Makefile.am, content/sifixes/Makefile.mingw, content/sifixes/src/cutscenes/moonshade_banquet.uc, content/sifixes/src/header/constants.uc, content/sifixes/src/header/si/si_gflags.uc, content/sifixes/src/usecode.uc
Fixes #118 SI: mage banquet breaks rejoin of partymembers if they are invisible
=> Fix re-joining of invisible party members after Moonshade banquet

actors.cc
Matches original behavior.
Fixes #307 U7-BG/SI: Poisonous enemies don't poison at all
=> Making snakes able to poison

actors.cc, usecode/intrinsics.cc
Handle negative exp bonuses in set_npc_prop intrinsic
Also add exp cap of 999,999 from original games, and of 255 for training points.
Fixes #306 "U7-SI & SS + SI Fixes: Planting The Silver Seed == EXP penalty?!!"
=> Fix for #306 "U7-SI & SS + SI Fixes: Planting The Silver Seed == EXP penalty?!!"

gamewin.cc, objs/egg.cc
To Silence the compilers :
- `objs/egg.cc` : Replace a `virtual` keyword by an `override`, add a few `ignore_unused_variable_warning` macros.
- `gamewin.cc` : Set default SFX value to -1.
To rework SFX #498 : 
- `gamewin.cc` : Fix if test, Do not emit SFX if left to -1 and do not prepare a repeat,  Increase SFX volume to MAX - 64
For discussion in issues #503 and #510
=> Rework Issue SFX #498 Fix, Silence Compiler warnings

audio/Midi.cc, audio/midi_drivers/ALSAMidiDriver.cpp, audio/midi_drivers/FMOplMidiDriver.cpp, audio/midi_drivers/LowLevelMidiDriver.cpp, gamewin.cc, gamewin.h, msvcstuff/vs2019/msvc_include.h, objs/chunks.cc, objs/chunks.h, objs/egg.cc, shapeid.cc
This completes the replacement of `clang-format` version 17, used up to mid-April 2024, by `clang-format` version 18, by agreement in Issue #514.
**For reviewers :** The one change that I feel funny is `new MT32Timbre* [128] {};` packed into `new MT32Timbre*[128]{};`.
I can obtain  `new MT32Timbre*[128] {};` instead with `SpaceBeforeCpp11BracedList: true` instead of `false` in `.clang-format`.
- But then all brace initializers get a new space like `const std::array frames{` becoming `const std::array frames {` or `actions = new Actor_action*[5]{` becoming `actions = new Actor_action*[5] {` in `actions.cc`. In total this makes more that 500 changes in more than 60 files.
- Also in `actions.cc` there are initializers with parentheses and initializers with braces. With this spacing the …
=> Switch Exult to clang-format version 18

mapedit/tools/mockup/Makefile, mapedit/tools/mockup/main.c, mapedit/tools/smooth/INSTALL, mapedit/tools/smooth/Makefile, mapedit/tools/smooth/config.c, mapedit/tools/smooth/globals.h, mapedit/tools/smooth/image.c, mapedit/tools/smooth/plugin.c, mapedit/tools/smooth/plugins/plugin_randomize.c, mapedit/tools/smooth/plugins/plugin_smooth.c, mapedit/tools/smooth/plugins/plugin_stream.c, mapedit/tools/smooth/smooth.conf
- `mapedit/tools/mockup + smooth/Makefile` :  Create a Makefile for all, tests, clean
- `mapedit/tools/mockup + smooth/ any .c` : Migrate to SDL 2, Support paletted images with less than 8 bits per pixel,       Fix exchanged arguments to `SDL_CreateRGBSurfaceFrom`, Remove a wrong `free`, remove the corresponding `malloc`,
- `mapedit/tools/smooth/smooth.conf` : Complete the missing color transform into smoothed.bmp, 
-  `mapedit/tools/smooth` sources and plugins : Rework the logic to use `Uint32` instead of `char[7]` for colors, Handle a "*" trigger accordingly.
=> Bump smooth and mockup to SDL 2

mapedit/chunklst.cc, mapedit/chunklst.h, mapedit/exult_studio.glade, mapedit/objbrowse.cc, mapedit/u7shp.cc
For Exult SDL2 / Studio GTK+ 3:
- `mapedit/chunklst.h + chunklst.cc` : Draw a Chunk look alike drag icon when dragging a Chunk, with an `Image_buffer8` target argument to `render_chunk`, and with the `render_chunk` rendered Chunk as the drag icon of a dragged Chunk,
- `mapedit/exult_studio.glade` : Remove the `gtk-ok` ( OK and Apply buttons ) and `gtk-cancel` ( Cancel buttons ) stock icons, Move the `gtk-edit` icon to `document-edit` and the `gtk-close` to `window-close`,
- `mapedit/objbrowse.cc + u7shp.cc` : Move the `gtk-cancel` icon to `window-close`.
This is a retrofit of the same changes in Studio GTK 4. The stock icons cannot be found with the default `Adwaita` theme and GTK 4 contrarily to GTK+ 3 does not provide replacements.
=> Give a look like icon when dragging a Chunk, Fix gtk- icons

cheat_screen.cc, cheat_screen.h, gumps/Gump_manager.cc, gumps/Gump_manager.h, gumps/VideoOptions_gump.cc, gumps/Yesno_gump.cc, gumps/Yesno_gump.h, msvcstuff/vs2019/msvc_include.h, palette.cc, palette.h, shapeid.cc, shapeid.h, version.cc, version.h
The PR adds mouse and touch support to the Cheat screen. Primarily it does this by Creating hot spots for each menu item that can be clicked. The hot spots are the Bracketed Key indicators on each menu item. For small touch devices the hot spots may be a bit small so the pre-existing method of using the On screen keyboard to select menu item can still be used. As part of adding hot spots I added highlights to the hotspots for when the mouse hovers over them. 
I also added an additional highlight that will highlight the entire menu item when it is selected. This only works for Menu items that do not switch to a new menu. Hover highlight is red, activation highlight is blue and both at the same time give purple
Double clicking/tapping will now act as pressing the return key provided the …
=> Adding Mouse and Touch support to Cheat screen and other cheat screen changes

Makefile.mingw
Alter `Makefile.mingw` to support building Exult and Studio using CLang in 32 and 64 bits, and using GCC 64 bits based on UCRT in Windows.
- Expand the `MSYSTEM` switch from `MINGW32` and `MINGW64` to `CLANG32`, `CLANG64` and `UCRT64`,
- Set `CC` and `CXX` to `gcc` and `g++` or to `clang` and `clang++` according to `MSYSTEM`,
- Set the CLang supported `WARNINGS`,
- Remove the build of `exult_studio.exp` by `dlltool` - which CLang does not support well, is not needed anyway.
=> Build Exult and Studio as CLang 32 and 64 by MinGW for Windows

.github/workflows/ci-windows.yml, Makefile.mingw, win32/exconfig.cc, win32/exult_installer.iss, win32/exult_studio_installer.iss, win32/exult_tools_installer.iss
- The workflow `ci-windows` is matriced to test build `MINGW64` and `CLANG64`.
The package install step receives a package name prefix to become MinGW environment independent.
- The build of `exconfig.dll` avoids the use of the Export definition file `exconfig.def` and the link option `--add-stdcall-alias` that CLang does not support.
The public entry points of `exconfig.dll` to the Inno Setup script `Get + SetExultGamePaths`, `VerifySI + BGDirectory` are switched from `stdcall` to `cdecl` to remove the need of the file `exconfig.def` and the option `--add-stdcall-alias`.
=> Test build ci-windows should build in MINGW64 and CLANG64

version.cc
Here is one syntax error need to be fixed.
=> Fix syntax error when compile on riscv.

desktop/info.exult.exult.metainfo.xml, desktop/info.exult.exult.releases.xml
These files are what the FreeDesktop project describes as "catalog metadata", for display in graphical package managers. Primarily this would be used for the Flatpak distribution to render the project's page on the FlatHub listing (e.g. https://flathub.org/apps/io.itch.amcsquad.amcsquad), but if a Linux distribution vendor opted to create a system package for Exult they could also include these files so that package managers can display the same metadata.
The release info here is currently manually maintained and again would be used to display release information on Flathub; I'm currently working on a GitHub Action to automatically update the release info on AppStream catalog metadata files like these when a release is created. I'll add another PR to implement this when I'm done with that …
=> Add AppStream metadata and release info

content/sifixes/src/cutscenes/fawn_trial.uc
Sometimes (not easily reproducible), the second part of the Fawn Trial cut scene hangs after Lady Yelinda remarks that Kylista is not around. This is because in those cases, she has the ASLEEP flag set and the usecode she is supposed to run (saying "Zulith...") checks if somebody can talk beforehand, which is not the case for sleeping NPCs. In order to fix this, clear the ASLEEP flag for her in case it is set at the beginning of the cutscene.
Fixes: #569
=> Sifixes: Fix possible hang in Fawn Trial cut scene.

content/sifixes/src/npcs/topo.uc, content/sifixes/src/usecode.uc
Topo has schedule 26 (eat at inn) for 12PM-3PM, but the location of that business activity is where he works (Ducio's shop), so if you talk to him and ask him about buying something or selling him gems he will claim that he is not at work - which is technically correct cause he is eating at the inn... Fix that by resetting the location of his eat at inn schedule to the Blue Boar.
Fixes: #572
=> Sifixes: Add fix for Topo's schedule.

.github/workflows/ci-windows.yml, .github/workflows/snapshots-windows.yml, .github/workflows/snapshots.yml, Makefile.mingw, README.win32, configure.ac, mapedit/Makefile.am, mapedit/gimpwin32.txt, mapedit/u7shp-old.cc, win32/exult_shpplugin_installer.iss
Commit 1 of 1:
configure.ac
Switch the Gimp requirement from 2 to 3
Build the Gimp 2 or Gimp 3 plugin depending on the installed Gimp
Die gracefully when asked to buid the plugin but Gimp is not installed
Install the plugin into the user location with --enable-gimp-plugin=user
Linux and al : ~/.config/GIMP/x.0/plug-ins/[u7shp/]
MacOS : ~/Library/Application Support/GIMP/x.0/plug-ins/[u7shp/]
Makefile.mingw
Switch the Gimp requirement from 2 to 3
Build the Gimp 2 or Gimp 3 plugin depending on the installed Gimp
Die gracefully when asked to buid the plugin but Gimp is not installed
Ensure the libgcc and the libstdc++ are statically linked
Add pluginclean to allclean
Fix comment in the CLANGARM64 branch
mapedit/Makefile.am
Ensure that u7shp get stored into the bin folder of the Exult install …
=> Migrate the Shape loader / exporter from Gimp 2 to Gimp 3

.github/workflows/ci-omnios.yml
- `ci-omnios.yml` : Refresh bootstrap, install CLang above LLVM, switch `configure` to CLang
=> Switch proof build of Exult / Studio on OmniOS from GCC to CLang

configure.ac, tools/Makefile.am, tools/x-shapefile.xml
The aim is to remove the need to be root when installing the Shape Thumbnailer as it installs two configuration files into `/usr/share` :
- `configure.ac`
```
Add an optional target to the --enable-gnome-shp-thumbnailer option into GTHUMB_PREFIX
system or (default) yes : /usr/share       ( requires root at install )
local                   : /usr/local/share ( requires root at install )
user                    : ~/.local/share
ingame                  : <Exult>/share ( requires adding that folder to XDG_DATA_DIRS )
```
- `tools/x-shapefile.xml`
Increase the priority to 60 to pass over another .SHP file type
- `tools/Makefile.am`
Rework the installation of the configuration files and the `update-mime-database` step using `GTHUMB_PREFIX`
- The option inventory of …
=> Permit alternate installation folders for the Shape Thumbnailer configuration files

.github/workflows/snapshots-windows.yml, Makefile.mingw, win32/exult_shpplugin_installer.iss
This removes the need of the dependent DLLs `libgcc_s_seh-1.dll` and `libstdc++-6.dll`.
- `.github/workflows/snapshots-windows.yml` : Bring pacman packages from `mingw-w64-clang-x86_64`, Use MSys2 variant `CLANG64`,
- `Makefile.mingw` : For safety during the build, deploy the CLang `libc++.dll` with the plugin into the `C:\GimpPlugin` folder along with `u7shp.exe` in case Gimp is built using GCC,
- `win32/exult_shpplugin_installer.iss` : The build of the plugin build in the Windows **snapshot** uses CLang64 like the build of Gimp : Remove the dependent DLLs from the installation script.
=> Build the Windows Snapshot with CLang64

mapedit/chunklst.cc
Fixes #449 
When you add or duplicate a chunk, the new chunk is not placed at the bottom of the chunk list. This messes up chunk groups as these aren't updated on add/duplicate
=> Move new chunks to end of list only

actions.cc, actions.h
Fixes #373
When the Avatar "runs" (via mouse movement) against a closed door, he will open it, go through, turn to the door, close it, turn away. This was bugged as in the Avatar opened and closed it twice, moving through the locked door at times.
=> Fix double automatic door opening

gumps/Notebook_gump.cc, gumps/Notebook_gump.h
Line breaks when you are reaching the end of a line via text input, adding autonotes or loading saved notes. Also avoids writing "^" as this crashed Exult.
Fixes #492
=> Notebook Gump proper line breaks

gamemgr/modmgr.cc
Error : `src_dir` not defined
Fixing by harmonizing the `src_dir` handling like the other ones.
But I'm not sure this is the right fix, because of the comment on line:
https://github.com/exult/exult/blob/13cb82a544d0b807e9e18f7091479994a0bfee10/gamemgr/modmgr.cc#L184
Please review and advise for the proper fix.
=> Fix compilation when DEBUG_PATHS is defined

.github/workflows/ci-android.yml, Makefile.am, android/app/src/main/cpp/dependencies/exult/CMakeLists.txt.in, audio/Makefile.am, audio/midi_drivers/FluidSynthMidiDriver.h, audio/midi_drivers/Makefile.am, configure.ac, files/zip/Makefile.am, gamemgr/Makefile.am, gumps/Makefile.am, mapedit/Makefile.am, objs/Makefile.am, shapes/Makefile.am, usecode/Makefile.am
-  `audio/midi_drivers/FluidSynthMidiDriver.h` : Reindent FluidSynth/FluidLite initial detection
- `Makefile.am` in `audio/(midi_drivers/)` + `gamemgr/` + `gumps/` + `mapedit/` + `obj/` + `shapes/` + `usecode/` + `files/zip/` + `./` :
Remove VORBIS, Add ALSA + FLUIDSYNTH + FLUIDLITE + ZLIB
Rename _INCLUDES to _CFLAGS
- `configure.ac` :
Remove spurious AC_SUBST as made by PKG_CHECK_MODULES
Check if want : Follows --enable options, then checks dependencies
Check if can  : After check for dependencies
Replace `gimptool` by `pkg-config`
Remove Android handling of FreeType2, is only queried with Want Studio
Remove check for `zlib.h`, is provided by zlib
=> Cleanup configure.ac and all Makefile.am

.github/workflows/snapshots-windows.yml
Some fixes for the Windows Snapshot Workflow
First no longer install mingw-w64-i686-SDL2_image and instead download and install https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.8/SDL2_image-devel-2.8.8-mingw.tar.gz  for i686
Also added work around for CMake 4 error with libmt32emu by adding -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to the command to tell Cmake to treat  CMakeLists as if it is version 3.5 and not the no longer supported 2.8.12 as specified in the file
=> Windows Snapshot Fixes

.github/workflows/ci-freebsd.yml, .github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml, .github/workflows/ci-omnios.yml, .github/workflows/codeql.yml, .github/workflows/coverity-scan.yml, android/app/src/main/cpp/dependencies/exult/CMakeLists.txt.in, tools/smooth/config.c, tools/smooth/config.h, tools/smooth/globals.h, tools/smooth/image.c, tools/smooth/image.h, tools/smooth/plugin.c, tools/smooth/plugin.h, tools/smooth/plugins/plugin_randomize.c, tools/smooth/plugins/plugin_smooth.c, tools/smooth/plugins/plugin_stream.c
- `.github/workflows/ci- freebsd + linux + macos + omnios .yml + coverity-scan.yml`
Install SDL2_image to enable the build of Smooth and Mockup,
Remove the `--disable-oggtest` and `--disable-vorbistest`, were valid with XIPH `ogg.m4`  + `vorbis.m4`.
- `android/app/src/main/cpp/dependencies/exult/CMakeLists.txt.in`
Remove the `--disable-oggtest` and `--disable-vorbistest`, were valid with XIPH `ogg.m4` + `vorbis.m4`.
- `tools/smooth/` various `.c + .h`
Add missing `const` to pass the builds, since the warning options of the mainline Exult are stricter than the specific options for Smooth and Mockup.
=> Build Smooth and Mockup tools during GitHub actions

actors.cc
During List Field fighting, the party member fights against all knights. Once the current opponent has been defeated, it does not die but flees as the tournament flag is set. However, the party member has been pursuing this fleeing opponent endlessly, trying to hit it. But even if they hit, they will not make any more damage due to the active tournament flag. Any other knights are ignored and they will eventually win against the party member.
To fix this, clear the target before we call the "died" usecode, so that the party member can select a new foe.
Fixes: #571
=> Fix List Field fights

actors.cc
Already slain NPCs will not teleport (especially after the banes are released, this would leave duplicate bodies of already dead NPCs)
=> Fixes #663

mouse.cc
Fix #389
Mouse speed changes in a square around the Avatar of half the game window height but a minimum of 200x200. Outside of this square it's fast_speed (unless hostiles, combat...)
=> Mouse speed rectangle

flic/playfli.cc, game.cc, gamemgr/bggame.cc, gamemgr/sigame.cc, gamerend.cc, gamewin.cc, imagewin/BilinearScaler.cpp, imagewin/BilinearScaler.h, imagewin/BilinearScalerInternal.h, imagewin/BilinearScalerInternal_2x.cpp, imagewin/BilinearScalerInternal_Arb.cpp, imagewin/BilinearScalerInternal_X1Y12.cpp, imagewin/BilinearScalerInternal_X2Y24.cpp, imagewin/imagewin.cc, imagewin/imagewin.h, menulist.cc, msvcstuff/vs2019/Exult.vcxproj, msvcstuff/vs2019/msvc_include.h
After way too many months works here are my scaler related fixes and changes primarily to fix The BlackLine problem in #543 
This set of changes removes Source buffer restrictions from the Bilinear scaler that was a big part of the underlying problem in #543 I also somewhat refactored the Bilinear scaler code replacing Macros with inline functions and added more comments in an attempt to make this code slightly more understandable and maintainable. The bilinear scaler used to require source buffer to have a multiple of 4 pixel alignment and Image_window::show would round down buffer sizes to a multiple of 4 which would affect all scalers when using a game window size that had non multiples of 4. As the round down was only needed for that version of bilinear scaler I removed the round down …
=> Scaler changes and fixes

keys.cc, keys.h
The keybinding parser should have printed out line numbers on errors but didn't. Now it prints the line number and the offending line itself.
Also fixes a problem when parsing pathkeys: empty lines were no longer skipped.
=> Better error handling in parsing keybindings

mapedit/combo.cc
Allowing bigger combos. With today's screen real estate, 32x32 is rather small. Tested and this small change allows creating, saving and dropping bigger combos in Exult. Fixes #103
=> Allowing bigger combos

cheat.h, exult.cc, mapedit/exult_studio.glade, mapedit/studio.cc, mouse.cc, server/servemsg.h, server/server.cc
Allows mass selecting objs without the need to hold down CTRL.
Basically the same as Pick for combo, except it doesn't open a new Combo
=> A new Exult Studio Mode: Pick for edit

gamemap.cc
Just a small change to remove the 4 bit lift limitation from v2 Exult Extended format IFIXes. Exult would always save V2 IFIXES with 8 Bit lift but would mask it to 4 bit when loading. These changes also forces All new IFIXes to be written as V2 so 8 bit lift is always supported
closes  #684
=> Allow IFIXes to have 8 bit lift

desktop/info.exult.exult.studio.svg, desktop/info.exult.exult.svg
For some reason, the presence of the `xml:space="preserve"` attribute on the main `svg` tag in these two images broke rendering of the files in a browser: https://raw.githubusercontent.com/exult/exult/3ecbcdcc181a9edca13d3201875c04dfc7c9163f/desktop/info.exult.exult.studio.svg
This fixes it: https://raw.githubusercontent.com/fpiesche/exult/622d4d30f7eb853f83cee03dc45943dfe0c5a2d1/desktop/info.exult.exult.studio.svg
I've also added the xmlns attributes for good measure. I don't think they're malformed without them but the consistency is nice to have.
=> Fix SVG attributes for raw display

audio/Audio.cc, audio/Audio.h, combat.cc, combat.h, gamewin.cc, keyactions.cc, mouse.cc
Move start_music_combat from Audio code to combat code (fixes #734).
When monsters attack while danger music is playing transition to track 11 (fixes #725).
Running away from monsters plays track 18 (partially fix for #723.
is_hostile_nearby() will work even if the player is in god mode, which allows danger music to play in god mode.
Moved danger music into combat.cc but it's still being polled in gamewin's Background_noise::handle_event(). This gives finer control over the danger tracks, for example only playing it once.
=> Combat tracks fixes

browser.cc, cheat_screen.cc, cheat_screen.h
In game shape browser can show shapes of patched vga files (fixes #728).
Cheat screen will not wait for the release of the key B after you used the shape browser to change shape or to polymorph.
=> Fix for #728 - in game shape browser not handling patched vga files

ios/Exult.xcodeproj/project.pbxproj, ios/Exult.xcodeproj/xcshareddata/xcschemes/git_clone_master_dependencies.xcscheme, ios/Exult.xcodeproj/xcshareddata/xcschemes/git_clone_release_dependencies.xcscheme, ios/include/config.h, ios/libfluidsynth.xcodeproj/project.pbxproj
Switching iOS back to FluidSynth master from FluidLite master. FluidSynth master now allows building without GLib dependency.
=> Switching iOS back to FluidSynth

.github/workflows/snapshots.yml, Makefile.common, configure.ac, exult.cc, files/crc.cc, files/crc.h, files/zip/unzip.cc, files/zip/unzip.h, gamedat.cc, gamemgr/modmgr.cc, gamemgr/modmgr.h, ios/Info.plist, ios/include/config.h, mapedit/studio.cc, msvcstuff/vs2019/msvc_include.h, tools/aseprite_plugin/package.json, win32/crash.cc, win32/exconfig.rc, win32/exult_installer.iss, win32/exult_shpplugin_installer.iss, win32/exult_studio_installer.iss, win32/exult_tools_installer.iss, win32/exultico.rc, win32/exultstudioico.rc
This PR is to add integrated mod and data installers into Exult itself.
This primary drive was to remove the need to use Windows shell code in our Windows Installer to unzip the mods and data that would not work in wine.
closes #746 
2 new command line options are added `--installdata <zipfile>` and `--installmod <zipfile>`
`--insatalldata` is quite simple, all it does is extract the zip file argument into `<data>`
`--installmod` does quit a bit more, it looks in the root of the zip for modcfg files.  For each modcfg found, it checks Required_version and prints a warning if the mod is incompatible, but it will still install the mod as Exult itself Shouldn't show incompatible mods in the menu. It will then attempt to figure out what game to install the mod to by getting the identity from …
=> Integrated installers

Makefile.am, Makefile.common, Makefile.mingw, docs/playscene.txt, gamemgr/bggame.cc, gamemgr/sigame.cc, ios/Exult.xcodeproj/project.pbxproj, msvcstuff/vs2019/Exult.vcxproj, msvcstuff/vs2019/Exult.vcxproj.filters, playscene.cc, playscene.h, txtscroll.cc, txtscroll.h
First of full disclosure, this PR was done with lots of help by Github Copilot and this shows in the way the code is constructed.
Playscene allows creating scripted cutscenes using the media Exult knows how to handle.
Namely FLIC animations, audio files OGG, WAV, VOC and also playback of a games'
music and sfx tracks.
To start a scripted scene use
```
if (scene_available("name")) {
play_scene("name");
}
```
`scene_available("name")` looks for the files name_info.txt and name.flx in
a game's or a mod's patch folder, which play_scene("name") will play back.
Exult will automatically look for intro, endgame, quotes and credits
cutscenes in the above mentioned folders (files: intro_info.txt,
intro.flx, endgame_info.txt, ...) and play these instead of the orignal.
The script is loosely based on …
=> Create scripted cutscenes

docs/playscene.txt, gamemgr/bggame.cc, gamemgr/sigame.cc, playscene.cc, playscene.h
Playscene improvements:
- subtitle colors can be chosen from the flic's palette and have a black outline.
- subtitles can be placed either on bottom, center or top.
- start of audio and subtitles is now timed in ms instead of frames, a stop time is now also possible.
=> Playscene fixes

exult.cc, gamewin.cc, gumps/Face_stats.cc, gumps/ShortcutBar_gump.cc, usecode/Makefile.am, usecode/ucinternal.cc, usecode/ucmachine.h
Hide UI elements (face stats, shortcuts bar, virtual joystick) during the first scenes in BG and SI.
When the respective global flags are set (0x3b in BG and 0x03 in SI) these are shown if configured to.
=> Hide UI elements (face stats, shortcuts bar, virtual joystick) during the first scenes in BG and SI

usecode/conversation.cc, usecode/intrinsics.cc
Also close all gumps on SI's scripted crystal ball scenes.
This seems to work on all SI scenes (tested wall of lights, Petra body switch, crystal ball scenes).
If you have any idea what to test, additionally, please let me know.
It could also be used for the scripted SI first scene as it starts out with setting main_actor_dont_move and clears the flag at the appropriate time. So no need to toggle the UI elements on a specific global flag. I would take a look at it if/when this gets merged.
=> Hide UI during scripted scenes.

android/app/src/main/java/info/exult/ExultActivity.java, android/lib/include/TouchUI_Android.h, android/lib/src/TouchUI_Android.cc, exult.cc, gamewin.cc, ios/GamePadView.m, ios/include/ios_utils.h, ios/ios_utils.mm, touchui.h
Android and iOS now have a button to pause combat, right next to the ESC button. When paused a long touch on a party member selects them so you can direct them at a target to attack (same as right click on the desktop).
Also fixed the issue on iOS that didn't properly switch the ESC button when the dpad screen location was changed to the left side. Additionally the dpad had no margin when on the left side.
Fixes #784 and #785
=> Mobile pause button when combat allows pausing

android/app/src/main/java/info/exult/ArchiveStreamFactoryWithXar.java, android/app/src/main/java/info/exult/ContentInstallerFragment.java, android/app/src/main/java/info/exult/CustomModInstaller.java, android/app/src/main/java/info/exult/ExultActivity.java, android/app/src/main/java/info/exult/ExultContent.java, android/app/src/main/java/info/exult/ExultGameContent.java, android/app/src/main/java/info/exult/GamesFragment.java, android/app/src/main/java/info/exult/PatchInstaller.java, android/app/src/main/java/info/exult/ViewPagerAdapter.java, android/app/src/main/res/values/games_card_strings.xml
One button to install any Ultima VII game, only list installed games and recognize officially localized games (crc32 checking of mainshp.flx instead of initgame.dat). Localized games install to 'blackgate' or 'serpentisle', so you can only have one of each games without addons. Also fixed several deprecations.
Fixes #799
=> Android: reworked the launcher's installer.
