- actors.cc
- combat.cc
- effects.cc
- effects.h
- gamewin.cc
- objs/egg.cc
- objs/objs.cc
- usecode/intrinsics.cc
Replace 2nd handcrafted linked list with std::list and take advantage of RAII.
> Effects_manager: store effects is std::list

- files/utils.cc
MacOS APIs with `Create` or `Copy` in their name give ownership, thus requiring to call CFRelease on them. This commit does that using RAII idiom.
> Fix memleak on MacOS

- Exult_Removal_of_X11_Connection_Number.md
- Exult_Removal_of_X11_Drag_and_Drop.md
- Makefile.am
- configure.ac
- exult.cc
- gumps/gump_utils.h
- mapedit/chunklst.cc
- mapedit/combo.cc
- mapedit/npclst.cc
- mapedit/paledit.cc
- mapedit/shapedraw.cc
- mapedit/shapelst.cc
- server/server.cc
- shapes/u7drag.cc
- shapes/u7drag.h
> Exult x11 dependencies

- drag.cc
- drag.h
Turns out this was an unused leftover; removing it completely.
> Remove unused class field

- tqueue.cc
Reverting a breaking change I have introduced while working on time queue.
Turns out, that if one opens a gump during combat,
sometimes the time would completely stop in the game (cheat mode would
keep showing same hour). Relatively easily reproducible with mages
and fighters near bee cave in Yew, especially when mages cast
paralysis when invisible; also applicable to dragons in Destard.
I will invesitgate it more later; so far just taking back the breaking change in full.
> Revert activate_always to prevent freezing time

- files/utils.cc
- gamemgr/bggame.cc
resolves #90
also updates the address to twitter.
> added congratulations screen

- Makefile.am
- acinclude.m4
- configure.ac
- sdl_main.cc
Add support for detecting when we're cross-compiling for an android platform.
> Detect android builds

- exult.cc
- files/utils.cc
- files/utils.h
Use Internal Storage Path for the home folder on Android.
> Fix home path for android

- android/Makefile.am
- android/app/build.gradle.in
- android/app/src/main/cpp/CMakeLists.txt
- android/app/src/main/cpp/exult_android_main.cc
- configure.ac
This adds a skeleton for the C/C++ layer to the app that will eventually call into the Exult engine.
> Add NDK C/C++ skeleton

- Makefile.am
- android/Makefile.am
- android/app/src/main/java/info/exult/ExultActivity.java
- android/app/src/main/res/layout/launcher_card.xml
- android/lib/Makefile.am
- android/lib/include/TouchUI_Android.h
- android/lib/src/Makefile.am
- android/lib/src/TouchUI_Android.cc
- configure.ac
- exult.cc
This patch series adds the touch UI elements needed to interact with the game without a physical keyboard.
> Add Android touch UI elements

- cheat_screen.cc
- gamewin.cc
- gumps/Notebook_gump.cc
- gumps/VideoOptions_gump.cc
- version.cc
This patch series aligns behavior more with the iOS port and other minor platform cleanups
> Additional ifdef updates for Android

- android/README.md
Adding an overview of the Android port.
> Add a README.md for Android

- audio/midi_drivers/ALSAMidiDriver.cpp
From PR #238, missing cleanup code in the failing paths of `ALSAMidiDriver::open` in `audio/midi_drivers/ALSAMidiDriver.cc`.
Rationalize `ALSAMidiDriver::close` and call it from all failing paths of `ALSAMidiDriver::open`.
> Close properly ALSA when MIDI search fails

- mapedit/studio.cc
In `mapedit/studio.cc` :
- Replace `U7exists(EXULT_SERVER)` which no longer works on sockets by a `stat()`,
- Add `#include <sys/stat.h>` into the !_WIN32 section of includes
- Move into the !_WIN32 section + comment out the `#include <fcntl.h>`
to satisfy #251.
> Restore Studio to Exult communication on Unixes

- mapedit/npclst.cc
- mapedit/shapelst.cc
More fixes in the Zooming feature in Studio, about the Frames mode of the Shape Browser and the NPC browser
Fixes common to the Shape Browser and the NPC browser
- Make the Frame SpinButton sensitive only when a Shape or a Frame has been selected ( Frames and Shapes modes ),
- Track the first visible or the selected Frame when the Zooming changes ( Frames mode ),
- Fix the Visibility check, did not handle the Zooming ( Frames and Shapes modes ),
- Set the Horizontal Scroller initial value to 0, as the browser moves later to the first visible or the selected Frame ( Frame mode ).
Fixes specific to the Frame mode of the NPC Browser, leftover changes from when it was cloned out of the Shape Browser by commit 84c8cc69
- The selected frame was wrong when the display had been horizontally …
> Fix the Horizontal scrolling of the Shape and NPC browsers

- cheat_screen.cc
Rewrite previous commit 72eeab8 : No need for a ternary
> Rewrite cheat keyboard fix 

- configure.ac
Commit 1 of 1:
configure.ac
Run the compiler with --version to fetch and display its version
> In ./configure, Display the version of the Compiler

- .github/workflows/ci-msvc.yml
Adding a workflow file to test build Exult with MSVC. Because this doesn't use makefiles like everything else, I expect that if anyone adds or removes source files this will fail and I'll need to fix it. No IRC/Discord Notification for now, I'll add that once pulled because it needs the project secret
> Msvc workflow

- monsters.cc
This is a series of commits implementing the changes in my issue #273 [comment](https://github.com/exult/exult/issues/273#issuecomment-2023898241).
> Fixes for isssue #273

- actors.cc
Recursively prevent spells from being transferred to bodies.
> Fixes #300 Spell objects visible in normal game without cheats (U7-SI)

- gamewin.cc
Fixes #126 Exult Studio: Cannot create NPC past 355
> Fix segfault when creating NPC >= 356

- objs/find_nearby.h
Fixes #152 SI: Dreamrealm fight Batlin vs Avatar
> Add shape matching for polymorphed NPCs in find_nearby

- .github/workflows/ci-android.yml
- .github/workflows/snapshots-android.yml
- android/Makefile.am
- android/app/build.gradle.in
- android/app/src/main/AndroidManifest.xml
- android/gradle.properties
- configure.ac
Updating Android SDL2 release dependency and updating the manifest to allow Bluetooth connections to controllers
> Updating Android dependency and amnifest

- schedule.cc
Fix #378 complete
To sleep on a bedless spot, Exult will determine the sleep direction by checking whether the sleep frame's height fits. If there is no room it will default to the west-east frame.
> Fix #378 determine sleep direction without bed

- usecode/intrinsics.cc
- usecode/ucsched.cc
Fixes #384 
Enables the option to have speech + subtitles for three more cases
> Enables the option to have speech + subtitles for three more cases

- gumps/Book_gump.cc
- gumps/Scroll_gump.cc
- gumps/Text_gump.cc
Scrolls are displayed much more as in the original game.
> Fixes #497 Better scrolls display

- .github/workflows/ci-freebsd.yml
- .github/workflows/ci-linux.yml
- .github/workflows/ci-macos.yml
- .github/workflows/ci-omnios.yml
- .github/workflows/ci-windows.yml
- .github/workflows/codeql.yml
- .github/workflows/coverity-scan.yml
- .github/workflows/snapshots-windows.yml
- .github/workflows/snapshots.yml
- Makefile.mingw
- configure.ac
- docs/release.txt
- mapedit/Makefile.am
- mapedit/tools/aseprite_plugin/Makefile.am
- mapedit/tools/aseprite_plugin/Readme.txt
- mapedit/tools/aseprite_plugin/exult_shp.cc
- mapedit/tools/aseprite_plugin/main.lua
- mapedit/tools/aseprite_plugin/package.json
Imports shp files as png files and exports to shp files.
https://aseprite.org is a popular pixel art editor, both open source and commercial.
The plug-in works, but I'm not sure about the makefile.mingw additions (even though the converter exult_shp does build).
The integration in the Windows snapshot is not yet done.
> Aseprite plug-in

- desktop/info.exult.exult.metainfo.xml
- docs/xml/docs.xml
@DominusExult requested this via Discord when the Flatpak launched. Sorry I only got around to it now!
> Update documentation with information about Flatpak data locations

- actors.cc
Dead polymorphed NPCs should get their real dead body
> Fixes #679

- mapedit/shapelst.cc
Studio does not allow Export / Import All Frames on a Tile ( a terrain 8 x 8 shape ), and provides Edit Tiled instead.
This PR provides both Edit Tiled and Export / Import All Frames on a Tile :
- `mapedit/shapelst.cc` in `Shape_chooser::create_popup` : Do not filter out Export/Import All Frames on a Tile,
- `mapedit/shapelst.cc` in `Shape_chooser::import_all_pngs` : When Importing All Frames onto a Tile, check the pixel size of the PNGs beforehand, and reject an attempt to Import any PNG not 8 px x 8 px.
This PR satisfies the Issue #577
> Studio : Allow Export/Import All Frames on Tiles

- actions.cc
- actions.h
- schedule.cc
- schedule.h
Hammer and tongs will get placed on the table when not being used, troughs will be filled up from the well if available and troughs will be filled after being emptied. Sfx are still missing.
> forge_schedule is now matching and improving the original schedule.
